version: '3.8'
services:
  api:
    environment:
      - NODE_ENV:${NODE_ENV}
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['npm', 'run', 'start:${NODE_ENV}']
    env_file:
      - .env
    ports:
      - 8080:3000
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: '${POSTGRES_DB_PREFIX}_${POSTGRES_DB_NAME}'
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}
    volumes:
      - ./pgdata/data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgdata/pgadmin:/root/.pgadmin
    ports:
      - '5050:80'
